### PR TITLE
Update electron-builder

### LINKED ISSUE #2996: electron-builder 26.4.0 regression
With electron-builder 26.4.0, running `pnpm run build:unpack` emits a lot of warnings like:

```
  • detected workspace root for project using packageManager field  pm=pnpm config=pnpm@10.14.0+sha512.ad27a79641b49c3e481a16a805baa71817a04bbe06a38d17e60e2eaee83f6a146c6a688125f5792e48dd5ba30e7da52a5cda4c3992b9ccf333f9ce223af84748 resolved=/home/user/github/freedomofpress/securedrop-client/app projectDir=/home/user/github/freedomofpress/securedrop-client/app
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/@babel+runtime@7.28.6/node_modules/@babel/runtime: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/@babel+runtime@7.28.6/node_modules/@babel/runtime/package.json'
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/@dbmate+darwin-arm64@2.29.3/node_modules/@dbmate/darwin-arm64: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/@dbmate+darwin-arm64@2.29.3/node_modules/@dbmate/darwin-arm64/package.json'
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/@dbmate+darwin-x64@2.29.3/node_modules/@dbmate/darwin-x64: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/@dbmate+darwin-x64@2.29.3/node_modules/@dbmate/darwin-x64/package.json'
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/@dbmate+linux-arm@2.29.3/node_modules/@dbmate/linux-arm: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/@dbmate+linux-arm@2.29.3/node_modules/@dbmate/linux-arm/package.json'
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/@dbmate+linux-arm64@2.29.3/node_modules/@dbmate/linux-arm64: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/@dbmate+linux-arm64@2.29.3/node_modules/@dbmate/linux-arm64/package.json'
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/@dbmate+linux-ia32@2.29.3/node_modules/@dbmate/linux-ia32: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/@dbmate+linux-ia32@2.29.3/node_modules/@dbmate/linux-ia32/package.json'
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/@dbmate+win32-x64@2.29.3/node_modules/@dbmate/win32-x64: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/@dbmate+win32-x64@2.29.3/node_modules/@dbmate/win32-x64/package.json'
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/empty-package@file+empty-package/node_modules/empty-package: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/empty-package@file+empty-package/node_modules/empty-package/package.json'
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/@babel+runtime@7.28.6/node_modules/@babel/runtime: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/@babel+runtime@7.28.6/node_modules/@babel/runtime/package.json'
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/chownr@3.0.0/node_modules/chownr: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/chownr@3.0.0/node_modules/chownr/package.json'
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/yallist@5.0.0/node_modules/yallist: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/yallist@5.0.0/node_modules/yallist/package.json'
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/@types+node@22.19.7/node_modules/@types/node: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/@types+node@22.19.7/node_modules/@types/node/package.json'
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/undici-types@6.21.0/node_modules/undici-types: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/undici-types@6.21.0/node_modules/undici-types/package.json'
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/semver@6.3.1/node_modules/semver: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/semver@6.3.1/node_modules/semver/package.json'
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/fs-extra@8.1.0/node_modules/fs-extra: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/fs-extra@8.1.0/node_modules/fs-extra/package.json'
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/universalify@0.1.2/node_modules/universalify: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/universalify@0.1.2/node_modules/universalify/package.json'
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/jsonfile@4.0.0/node_modules/jsonfile: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/jsonfile@4.0.0/node_modules/jsonfile/package.json'
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/mimic-response@3.1.0/node_modules/mimic-response: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/mimic-response@3.1.0/node_modules/mimic-response/package.json'
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/@types+node@22.19.7/node_modules/@types/node: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/@types+node@22.19.7/node_modules/@types/node/package.json'
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/undici-types@6.21.0/node_modules/undici-types: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/undici-types@6.21.0/node_modules/undici-types/package.json'
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/semver@6.3.1/node_modules/semver: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/semver@6.3.1/node_modules/semver/package.json'
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/fs-extra@8.1.0/node_modules/fs-extra: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/fs-extra@8.1.0/node_modules/fs-extra/package.json'
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/universalify@0.1.2/node_modules/universalify: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/universalify@0.1.2/node_modules/universalify/package.json'
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/jsonfile@4.0.0/node_modules/jsonfile: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/jsonfile@4.0.0/node_modules/jsonfile/package.json'
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/mimic-response@3.1.0/node_modules/mimic-response: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/mimic-response@3.1.0/node_modules/mimic-response/package.json'
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/@babel+runtime@7.28.6/node_modules/@babel/runtime: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/@babel+runtime@7.28.6/node_modules/@babel/runtime/package.json'
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/empty-package@file+empty-package/node_modules/empty-package: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/empty-package@file+empty-package/node_modules/empty-package/package.json'
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/chownr@3.0.0/node_modules/chownr: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/chownr@3.0.0/node_modules/chownr/package.json'
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/yallist@5.0.0/node_modules/yallist: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/yallist@5.0.0/node_modules/yallist/package.json'
  • cannot find path for dependency  name=empty-package@empty-package reference=file:empty-package
```

And then when you try running the app it can't find those dependencies:
```
user@dev ~/g/f/s/app (main)> ./dist/linux-unpacked/securedrop-app --version
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'yallist'
Require stack:
- /home/user/github/freedomofpress/securedrop-client/app/dist/linux-unpacked/resources/app.asar/node_modules/tar/dist/commonjs/pack.js
- /home/user/github/freedomofpress/securedrop-client/app/dist/linux-unpacked/resources/app.asar/node_modules/tar/dist/commonjs/create.js
- /home/user/github/freedomofpress/securedrop-client/app/dist/linux-unpacked/resources/app.asar/node_modules/tar/dist/commonjs/index.js
- /home/user/github/freedomofpress/securedrop-client/app/dist/linux-unpacked/resources/app.asar/out/main/index.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:1390:15)
    at Module.s._resolveFilename (node:electron/js2c/browser_init:2:130480)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1032:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1037:22)
    at Module._load (node:internal/modules/cjs/loader:1199:37)
    at Module.c._load (node:electron/js2c/node_init:2:17993)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:244:24)
    at Module.require (node:internal/modules/cjs/loader:1470:12)
    at require (node:internal/modules/helpers:147:16)
```

With the help of Claude, I bisected this to electron-builder, and specifically 26.4.0. I didn't immediately find an upstream issue so I'm going to send a PR to downgrade for now and then we can report it upstream.

### PR DESCRIPTION
**Pull request by micahflee**
Fixes #2996

I updated electron-builder to the very latest version, 26.15.2, and the regression is magically gone. Also, as referenced in https://github.com/freedomofpress/securedrop-client/issues/2996#issuecomment-4090882571, I updated tar to the latest version too, which fixes many CVEs.

## Test plan

 `pnpm run build:unpack` shouldn't have any warnings:

```
❯ pnpm run build:unpack
[WARN] The "pnpm" field in package.json is no longer read by pnpm. The following keys were ignored: "pnpm.overrides". See https://pnpm.io/settings for the new home of each setting.

> securedrop-app@1.4.0-rc1 build:unpack /home/user/securedrop-client/app
> pnpm run build && electron-builder --dir


> securedrop-app@1.4.0-rc1 build /home/user/securedrop-client/app
> electron-vite build

Building in production mode
Using main vars: {
  __RENDERER_ONLY__: 'false',
  __IS_PRODUCTION__: 'true',
  __PROXY_CMD__: '""',
  __PROXY_ORIGIN__: '""',
  __VITE_NONCE__: '""'
}
vite v7.0.8 building SSR bundle for production...
✓ 19 modules transformed.
out/main/worker-BFj4zxwS.js   92.39 kB
out/main/index.js            123.84 kB │ map: 255.77 kB
✓ built in 413ms
vite v7.0.8 building SSR bundle for production...
✓ 1 modules transformed.
out/preload/index.js  6.11 kB │ map: 12.22 kB
✓ built in 43ms
vite v7.0.8 building for production...
✓ 4867 modules transformed.
../../out/renderer/index.html                                  0.32 kB
../../out/renderer/assets/inbox-empty-state-DHAdWWN3.svg       3.91 kB
../../out/renderer/assets/logo-BQgemeIF.png                   18.13 kB
../../out/renderer/assets/sign-in-background-DPb9oMgs.svg     24.41 kB
../../out/renderer/assets/index-C7XRGESl.css                  33.92 kB
../../out/renderer/assets/index-B9JEaub-.js                2,308.22 kB │ map: 4,764.01 kB
✓ built in 11.05s
  • electron-builder  version=26.3.0 os=6.18.31-1.qubes.fc41.x86_64
  • loaded configuration  file=/home/user/securedrop-client/app/electron-builder.yml
  • writing effective config  file=dist/builder-effective-config.yaml
  • skipped dependencies rebuild  reason=npmRebuild is set to false
  • packaging       platform=linux arch=x64 electron=41.5.0 appOutDir=dist/linux-unpacked
  • executing @electron/fuses  electronPath=dist/linux-unpacked/securedrop-app
```

Running the binary should work without error:

```
❯ ./dist/linux-unpacked/securedrop-app --version
SecureDrop Inbox v1.4.0-rc1
```

## Checklist

This change accounts for:
- [ ] testing changes on Qubes as needed (especially changes related to cryptography, export, disposable VM use, or complex UI changes)
- [ ] any needed updates to the [AppArmor profile] for files beyond the application code
- [ ] any needed [self-contained] database migrations (including testing against a clean test database from `main`)

[AppArmor profile]: https://github.com/freedomofpress/securedrop-client/blob/main/client/files/usr.bin.securedrop-client
[self-contained]: https://github.com/freedomofpress/securedrop-client/tree/main/client#generating-and-running-database-migrations

### CODE REVIEW

File: app/package.json [hunk 1]
```diff
@@ -66,7 +65,7 @@
     "@vitest/coverage-v8": "^3.2.4",
     "antd": "^5.29.3",
     "electron": "^41",
-    "electron-builder": "<26.3.1",
+    "electron-builder": "<26.15.2",
```
Comment (legoktm) [inline app/package.json]: We should switch to a ^ unless there's some reason to say below 26.15.2

File: app/pnpm-lock.yaml [hunk 2]
```diff
@@ -118,7 +118,7 @@ importers:
         specifier: ^41
         version: 41.5.0
       electron-builder:
-        specifier: <26.3.1
+        specifier: <26.15.2
         version: 26.3.0(electron-builder-squirrel-windows@26.0.12)
```
Comment (legoktm) [inline app/pnpm-lock.yaml]: This is still at 26.3.0

**Review by legoktm — CHANGES_REQUESTED** [review]
I don't see the electron-builder package actually being updated:

```
$ pnpm list electron-builder
Legend: production dependency, optional only, dev only

securedrop-app@1.4.0-rc1 /home/user/github/freedomofpress/securedrop-client/app

devDependencies:
electron-builder 26.3.0
```

I think you need to use a ^ constraint on a newer version to force the upgrade.

**Comment by micahflee** [comment]
Oops, got catch. I bumped electron-builder to `^26.15.3` now, and merged in main. It works without warnings:

```
❯ pnpm run build:unpack
[WARN] The "pnpm" field in package.json is no longer read by pnpm. The following keys were ignored: "pnpm.overrides". See https://pnpm.io/settings for the new home of each setting.

> securedrop-app@1.5.0-rc1 build:unpack /home/user/securedrop-client/app
> pnpm run build && electron-builder --dir


> securedrop-app@1.5.0-rc1 build /home/user/securedrop-client/app
> electron-vite build

Building in production mode
Using main vars: {
  __RENDERER_ONLY__: 'false',
  __IS_PRODUCTION__: 'true',
  __PROXY_CMD__: '""',
  __PROXY_ORIGIN__: '""',
  __VITE_NONCE__: '""'
}
vite v7.0.8 building SSR bundle for production...
✓ 19 modules transformed.
out/main/worker-DEmooeo9.js   92.75 kB
out/main/index.js            124.21 kB │ map: 256.59 kB
✓ built in 582ms
vite v7.0.8 building SSR bundle for production...
✓ 1 modules transformed.
out/preload/index.js  6.11 kB │ map: 12.22 kB
✓ built in 33ms
vite v7.0.8 building for production...
✓ 4867 modules transformed.
../../out/renderer/index.html                                  0.32 kB
../../out/renderer/assets/inbox-empty-state-DHAdWWN3.svg       3.91 kB
../../out/renderer/assets/logo-BQgemeIF.png                   18.13 kB
../../out/renderer/assets/sign-in-background-DPb9oMgs.svg     24.41 kB
../../out/renderer/assets/index-DCMCszhU.css                  34.15 kB
../../out/renderer/assets/index-Bx9aGYPY.js                2,312.87 kB │ map: 4,772.54 kB
✓ built in 7.82s
  • electron-builder  version=26.15.3 os=6.18.31-1.qubes.fc41.x86_64
  • loaded configuration  file=/home/user/securedrop-client/app/electron-builder.yml
  • detected workspace root for project using packageManager field  pm=pnpm config=pnpm@10.14.0+sha512.ad27a79641b49c3e481a16a805baa71817a04bbe06a38d17e60e2eaee83f6a146c6a688125f5792e48dd5ba30e7da52a5cda4c3992b9ccf333f9ce223af84748 resolved=/home/user/securedrop-client/app projectDir=/home/user/securedrop-client/app
  • writing effective config  file=dist/builder-effective-config.yaml
  • skipped dependencies rebuild  reason=npmRebuild is set to false
  • packaging       platform=linux arch=x64 electron=41.5.0 appOutDir=dist/linux-unpacked
  • downloading     label=electron
    [====================================================================================================] 100% | electron
  • downloaded electron zip extracted successfully  output=/home/user/securedrop-client/app/dist/linux-unpacked
  • searching for node modules  pm=pnpm searchDir=/home/user/securedrop-client/app
  • platform-specific optional dependencies not bundled — add them to your project's optionalDependencies if your app requires them (pnpm 10+ does not auto-install transitive platform binaries)  dependencies=["@dbmate/darwin-arm64@2.29.3","@dbmate/darwin-x64@2.29.3","@dbmate/linux-arm@2.29.3","@dbmate/linux-arm64@2.29.3","@dbmate/linux-ia32@2.29.3","@dbmate/win32-x64@2.29.3"]
  • executing @electron/fuses  electronPath=dist/linux-unpacked/securedrop-app

❯ ./dist/linux-unpacked/securedrop-app --version
SecureDrop Inbox v1.5.0-rc1
```

**Review by legoktm — APPROVED** [review]
LGTM, thanks. We can ship this in 1.6.0
