### PR TITLE
Don't assume all download failures are DownloadExceptions

### LINKED ISSUE #2274: `on_reply_download_failure()` assumes exceptions have a `uuid` attribute
## Description

After #2231, a `NoResultFound` exception can cause a further `AttributeError` in `securedrop_client.logic.Controller.on_reply_download_failure()`.

## Steps to Reproduce

Discovered in test runs of f6bd2c92ddb6a3c17b01a4e9c2a67ebdd05d44fe without this padding—

https://github.com/freedomofpress/securedrop-client/blob/f6bd2c92ddb6a3c17b01a4e9c2a67ebdd05d44fe/client/tests/functional/test_delete_sources.py#L32-L33

—suggesting that it's a race in downloading something that's been deleted.  After #2252, reproduce with:

```sh-session
cfm@kintsugi client % git diff tests/functional/test_delete_sources.py
diff --git a/client/tests/functional/test_delete_sources.py b/client/tests/functional/test_delete_sources.py
index cebf3ba5..d211e4d9 100644
--- a/client/tests/functional/test_delete_sources.py
+++ b/client/tests/functional/test_delete_sources.py
@@ -21,7 +21,6 @@ from tests.conftest import (
 
 
 @pytest.mark.parametrize("num_to_delete", [1, 3])
-@flaky
 def test_delete_sources(functional_test_logged_in_context, qtbot, mocker, num_to_delete):
     """
     Check that sources selected for deletion are first confirmed and then
@@ -29,9 +28,6 @@ def test_delete_sources(functional_test_logged_in_context, qtbot, mocker, num_to
     """
     gui, controller = functional_test_logged_in_context
 
-    # Wait for a full sync to give us a stable source list.
-    qtbot.wait(TIME_SYNC)
-
     def check_for_sources():
         """Check that we have enough sources to work with."""
         assert len(list(gui.main_view.source_list.source_items.keys())) >= num_to_delete
cfm@kintsugi client % rm tests/functional/data/test_delete_sources.yml 
cfm@kintsugi client % TESTS=tests/functional/test_delete_sources.py make test
```

## Expected Behavior

Either `on_reply_download_failure()` should only take a `DownloadException`, or it should not assume all exceptions it handles have a `uuid` attribute.

## Actual Behavior

```
ERROR tests/functional/test_delete_sources.py::test_delete_sources[3] - Failed: SETUP ERROR: Exceptions caught in Qt event loop:
________________________________________________________________________________
Traceback (most recent call last):
  File "/Users/cfm/Desktop/securedrop-client/client/securedrop_client/logic.py", line 919, in on_reply_download_failure
    reply = storage.get_reply(self.session, exception.uuid)
                                            ^^^^^^^^^^^^^^
AttributeError: 'NoResultFound' object has no attribute 'uuid'
________________________________________________________________________________
Traceback (most recent call last):
  File "/Users/cfm/Desktop/securedrop-client/client/securedrop_client/logic.py", line 919, in on_reply_download_failure
    reply = storage.get_reply(self.session, exception.uuid)
                                            ^^^^^^^^^^^^^^
AttributeError: 'NoResultFound' object has no attribute 'uuid'
```

### PR DESCRIPTION
**Pull request by legoktm**
## Status

Ready for review 

## Description

Exceptions can be other types, so we should use a wider type and isinstance checks. This brings `on_message_download_failure` and `on_reply_download_failure` in line with `on_file_download_failure`.

This is mostly a bandage over the regression seen in #2274 and doesn't really substitute for the lack of more coordinated error handling.

Fixes #2274.

## Test Plan

* [ ] without this PR, follow reproduction steps in https://github.com/freedomofpress/securedrop-client/issues/2274 and confirm it's failing
* [ ] check out this PR, retry reproduction steps in https://github.com/freedomofpress/securedrop-client/issues/2274 and it should pass
* [ ] visual review

## Checklist

 - [x] These changes should not need testing in Qubes

### CODE REVIEW

**Comment by legoktm** [comment]
> One minor suggestion is that if we're adding a wildcart exception detection at the end, that we do it in all methods or find a generic way to do so. But that may be beyond this PR.

I agree, and Ro has said the same as well.
