### ISSUE TITLE
electron-builder 26.4.0 regression

### ISSUE THREAD

**Issue by legoktm** [freedomofpress/securedrop-client#2996]
With electron-builder 26.4.0, running `pnpm run build:unpack` emits a lot of warnings like:

```
  • detected workspace root for project using packageManager field  pm=pnpm config=pnpm@10.14.0+sha512.ad27a79641b49c3e481a16a805baa71817a04bbe06a38d17e60e2eaee83f6a146c6a688125f5792e48dd5ba30e7da52a5cda4c3992b9ccf333f9ce223af84748 resolved=/home/user/github/freedomofpress/securedrop-client/app projectDir=/home/user/github/freedomofpress/securedrop-client/app
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/@babel+runtime@7.28.6/node_modules/@babel/runtime: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/@babel+runtime@7.28.6/node_modules/@babel/runtime/package.json'
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/@dbmate+darwin-arm64@2.29.3/node_modules/@dbmate/darwin-arm64: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/@dbmate+darwin-arm64@2.29.3/node_modules/@dbmate/darwin-arm64/package.json'
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/@dbmate+darwin-x64@2.29.3/node_modules/@dbmate/darwin-x64: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/@dbmate+darwin-x64@2.29.3/node_modules/@dbmate/darwin-x64/package.json'
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/@dbmate+linux-arm@2.29.3/node_modules/@dbmate/linux-arm: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/@dbmate+linux-arm@2.29.3/node_modules/@dbmate/linux-arm/package.json'
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/@dbmate+linux-arm64@2.29.3/node_modules/@dbmate/linux-arm64: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/@dbmate+linux-arm64@2.29.3/node_modules/@dbmate/linux-arm64/package.json'
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/@dbmate+linux-ia32@2.29.3/node_modules/@dbmate/linux-ia32: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/@dbmate+linux-ia32@2.29.3/node_modules/@dbmate/linux-ia32/package.json'
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/@dbmate+win32-x64@2.29.3/node_modules/@dbmate/win32-x64: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/@dbmate+win32-x64@2.29.3/node_modules/@dbmate/win32-x64/package.json'
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/empty-package@file+empty-package/node_modules/empty-package: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/empty-package@file+empty-package/node_modules/empty-package/package.json'
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/@babel+runtime@7.28.6/node_modules/@babel/runtime: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/@babel+runtime@7.28.6/node_modules/@babel/runtime/package.json'
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/chownr@3.0.0/node_modules/chownr: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/chownr@3.0.0/node_modules/chownr/package.json'
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/yallist@5.0.0/node_modules/yallist: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/yallist@5.0.0/node_modules/yallist/package.json'
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/@types+node@22.19.7/node_modules/@types/node: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/@types+node@22.19.7/node_modules/@types/node/package.json'
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/undici-types@6.21.0/node_modules/undici-types: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/undici-types@6.21.0/node_modules/undici-types/package.json'
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/semver@6.3.1/node_modules/semver: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/semver@6.3.1/node_modules/semver/package.json'
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/fs-extra@8.1.0/node_modules/fs-extra: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/fs-extra@8.1.0/node_modules/fs-extra/package.json'
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/universalify@0.1.2/node_modules/universalify: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/universalify@0.1.2/node_modules/universalify/package.json'
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/jsonfile@4.0.0/node_modules/jsonfile: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/jsonfile@4.0.0/node_modules/jsonfile/package.json'
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/mimic-response@3.1.0/node_modules/mimic-response: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/mimic-response@3.1.0/node_modules/mimic-response/package.json'
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/@types+node@22.19.7/node_modules/@types/node: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/@types+node@22.19.7/node_modules/@types/node/package.json'
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/undici-types@6.21.0/node_modules/undici-types: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/undici-types@6.21.0/node_modules/undici-types/package.json'
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/semver@6.3.1/node_modules/semver: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/semver@6.3.1/node_modules/semver/package.json'
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/fs-extra@8.1.0/node_modules/fs-extra: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/fs-extra@8.1.0/node_modules/fs-extra/package.json'
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/universalify@0.1.2/node_modules/universalify: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/universalify@0.1.2/node_modules/universalify/package.json'
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/jsonfile@4.0.0/node_modules/jsonfile: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/jsonfile@4.0.0/node_modules/jsonfile/package.json'
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/mimic-response@3.1.0/node_modules/mimic-response: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/mimic-response@3.1.0/node_modules/mimic-response/package.json'
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/@babel+runtime@7.28.6/node_modules/@babel/runtime: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/@babel+runtime@7.28.6/node_modules/@babel/runtime/package.json'
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/empty-package@file+empty-package/node_modules/empty-package: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/empty-package@file+empty-package/node_modules/empty-package/package.json'
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/chownr@3.0.0/node_modules/chownr: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/chownr@3.0.0/node_modules/chownr/package.json'
  • Failed to read package.json for /home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/yallist@5.0.0/node_modules/yallist: ENOENT: no such file or directory, open '/home/user/github/freedomofpress/securedrop-client/app/node_modules/.pnpm/yallist@5.0.0/node_modules/yallist/package.json'
  • cannot find path for dependency  name=empty-package@empty-package reference=file:empty-package
```

And then when you try running the app it can't find those dependencies:
```
user@dev ~/g/f/s/app (main)> ./dist/linux-unpacked/securedrop-app --version
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'yallist'
Require stack:
- /home/user/github/freedomofpress/securedrop-client/app/dist/linux-unpacked/resources/app.asar/node_modules/tar/dist/commonjs/pack.js
- /home/user/github/freedomofpress/securedrop-client/app/dist/linux-unpacked/resources/app.asar/node_modules/tar/dist/commonjs/create.js
- /home/user/github/freedomofpress/securedrop-client/app/dist/linux-unpacked/resources/app.asar/node_modules/tar/dist/commonjs/index.js
- /home/user/github/freedomofpress/securedrop-client/app/dist/linux-unpacked/resources/app.asar/out/main/index.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:1390:15)
    at Module.s._resolveFilename (node:electron/js2c/browser_init:2:130480)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1032:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1037:22)
    at Module._load (node:internal/modules/cjs/loader:1199:37)
    at Module.c._load (node:electron/js2c/node_init:2:17993)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:244:24)
    at Module.require (node:internal/modules/cjs/loader:1470:12)
    at require (node:internal/modules/helpers:147:16)
```

With the help of Claude, I bisected this to electron-builder, and specifically 26.4.0. I didn't immediately find an upstream issue so I'm going to send a PR to downgrade for now and then we can report it upstream.
